PLUGIN_NAME=		easytier
PLUGIN_VERSION=		1.0
PLUGIN_COMMENT=		EasyTier P2P overlay network
PLUGIN_MAINTAINER=	your-email@example.com
PLUGIN_CATEGORIES=	net
PLUGIN_WWW=		https://easytier.rs

.include "../../Mk/plugins.mk"
